# @package _global_

# Folder names for data and metrics organisation
xp_name: glorys4_4dvar_test
data_name: processed_2019_global_4

# Your model type, for data preprocessing
MODEL_TYPE: 4DVARNET

paths:
  # Folders in which subfolders for your metrics will be created
  OSE_DATA_PATH: /DATASET/OCB_traces/
  METRICS_PATH: /DATASET/GLORYS12/metrics/

  # Folder where your leadtimes to evaluate are located
  rec_path: /DATASET/GLORYS12/rec/glorys4_global_movpatch_softedge_1y_fastrec/nrt_2019_global_4/

specs:
  # Time slice for data download and metrics computations
  min_time: 2019-03-01
  max_time: 2019-04-30
  time_day_crop: 0

  # Domain for data download
  min_lon: -180
  max_lon: 180
  min_lat: -80
  max_lat: 90

  #IMPORTANT: keep "{}" in place of satellite name in copernicus_dataset_id
  copernicus_dataset_id: cmems_obs-sl_glo_phy-ssh_my_{}-l3-duacs_PT1S
  ref_satellites: ['c2', 'h2ag', 'h2b', 'j3', 's3a', 's3b']

# Domains for metrics computation
metrics_spatial_domains:
  #GLOBE:
  #  lat:
  #    _target_: builtins.slice
  #    _args_:
  #    - -80
  #    - 90
  #  lon:
  #    _target_: builtins.slice
  #    _args_:
  #    - -180
  #    - 180
  GULFSTREAM:
    lat:
      _target_: builtins.slice
      _args_:
      - 32
      - 42
    lon:
      _target_: builtins.slice
      _args_:
      - -65
      - -55
  GROENLAND:
    lat:
      _target_: builtins.slice
      _args_:
      - 48
      - 58
    lon:
      _target_: builtins.slice
      _args_:
      - -35
      - -25
  MADERE:
    lat:
      _target_: builtins.slice
      _args_:
      - 32
      - 42
    lon:
      _target_: builtins.slice
      _args_:
      - -23
      - -13

options:
  # which parts should be skipped
  skip:
    data: False
    metrics: False

  # should downloaded/outputted data be overwritten
  overwrite:
    data: False
    metrics: True


entrypoints:
  - _target_: src.ose_pipeline.ose_full_pipeline.execute_full_pipeline
    min_time: ${specs.min_time}
    max_time: ${specs.max_time}
    min_lon: ${specs.min_lon}
    max_lon: ${specs.max_lon}
    min_lat: ${specs.min_lat}
    max_lat: ${specs.max_lat}
    metrics_spatial_domains: ${metrics_spatial_domains}
    time_day_crop: ${specs.time_day_crop}
    copernicus_dataset_id: ${specs.copernicus_dataset_id}
    ref_satellites: ${specs.ref_satellites}
    ose_data_path: ${paths.OSE_DATA_PATH}
    rec_path: ${paths.rec_path}
    metrics_path: ${paths.METRICS_PATH}
    xp_name: ${xp_name}
    data_name: ${data_name}
    model_type: ${MODEL_TYPE}
    skip: ${options.skip}
    overwrite: ${options.overwrite}

defaults:
  - _self_

